### ISSUE TITLE
Not working on Android/iOS

### ISSUE THREAD

**Issue by waletoyo1** [Princewil/flutter_paystack_plus#1]
Hi, the package works fine on flutter web but not on the android/ios app. I had to delete the logic for the web before it could work for android. Also, work on the black screen shows when you want to make a payment.

**Comment by Princewil** [comment]
Alright. I will work on that.

**Comment by Princewil** [comment]
The solution is to call platform specific dependency, so that the JS package is called only when its running on web and vice versa. 
If you find a way around that, pls let me know or you can work on it and send a request for a merger.

**Comment by Princewil** [comment]
Bug fixed!
