### ISSUE TITLE
Currency Not supported by Merchant

### ISSUE THREAD

**Issue by Jeff-Ayako** [Princewil/flutter_paystack_plus#10]
Hi am from Kenya am using live keys , my currency is KES on the web version of my app I keep getting an error titled we could not start this trascation, currency not supported by the merchant. kindly help.

**Comment by Princewil** [comment]
You will have to enable the currency on your Paystack dashboard.

**Comment by Princewil** [comment]
I want to believe this issue has been resolved. I will close it now. If you still have the issue please reopen.
Thanks.
