### ISSUE TITLE
Set default payment method to a specific one

### ISSUE THREAD

**Issue by Williamtobs** [Princewil/flutter_paystack_plus#14]
How do I change the initial payment method, I only want to use bank transfer as payment method.

**Comment by Princewil** [comment]
You can disable other options from your paystack dashboard. It will
automatically reflect via the package

**Comment by Williamtobs** [comment]
That is not feasible considering we still need other options from another page. Thanks anyway.

**Comment by Princewil** [comment]
You are welcome👍
