### ISSUE TITLE
onSuccess not called.

### ISSUE THREAD

**Issue by jeedy20** [Princewil/flutter_paystack_plus#2]
onSuccess or onClosed not called after a successful or declined transaction.

**Comment by Princewil** [comment]
Alright. I will looking into it.

**Comment by Princewil** [comment]
I don't think there is any issue with onSuccess or onClosed after my review.
Anyways, update your package, I made some improvement. 
Also check out this [example](https://github.com/Princewil/flutter_paystack_plus_example.git) repo.

If you still face similar issue, then reopen and send me screenshots and other important detail.

**Comment by Princewil** [comment]
@PurjaRipal You are having issues with the callback?

**Comment by PurjaRipal** [comment]
@Princewil  Yes sir,

after completed the payment i'm getting only payment successful screen but there is no callback to 

> onSuccess: ()

 of `FlutterPaystackPlus.openPaystackPopup` even i tried with your provided example project.

Could you please help me out on this ?

**Comment by Princewil** [comment]
Could you provide a screenshot of your code?

**Comment by PurjaRipal** [comment]
I just download this repo [https://github.com/Princewil/flutter_paystack_plus_example](url) and add my publicKey & secretKey there is no change in code sir.

**Comment by Princewil** [comment]
Are you running on mobile or on web?

Also did you include your "callbackurl" on the function?

**Comment by Princewil** [comment]
> I just download this repo [https://github.com/Princewil/flutter_paystack_plus_example](url) and add my publicKey & secretKey there is no change in code sir.

This example code is without the callback url and thus may not get the desirable results

**Comment by PurjaRipal** [comment]
Yes sir, running on mobile and don't have callbackurl right now

**Comment by Princewil** [comment]
That's the issue, for mobile a callback url is required (check the docs). 

How to get the callbackurl:
- Go your paystack console
- On your setting add a callback url
- Then in your code use the same url as your callbackurl
- Then try again

**Comment by PurjaRipal** [comment]
okay sir i'll try again and give you update by the way thank you on your immediate response.

**Comment by Princewil** [comment]
You are welcome sir 🫡

**Comment by PurjaRipal** [comment]
Thank you so much @Princewil sir. it works

**Comment by Princewil** [comment]
> Thank you so much @Princewil sir. it works

You are welcome 💪
