### ISSUE TITLE
Error in the popup and callbacks not firing - Web

### ISSUE THREAD

**Issue by saintjab** [Princewil/flutter_paystack_plus#20]
Hey, thanks for this library. It is promising. I am using version 2.2.0 and followed the example for setting up for web:
- adding the scripts to top of the body tag of web/index.html
- created paystack_interop.js in web folder and copied/pasted the paystackPopUp function
- Inside my widget on button clicked running 
`try {
      return await FlutterPaystackPlus.openPaystackPopup(
          publicKey: env == "my public key here",
          context: context,
          currency: 'NGN',
          customerEmail: "some user email here",
          amount: (100 * 10000).toString(),
          reference: "some ref here",
          callBackUrl: "",
          onClosed: () {
            debugPrint('Could\'nt finish payment');
            //doesn't not get called on cancelled/ failed
          },
          onSuccess: () {
            debugPrint('Payment successful');
            //doesn't not get called on successful payment either
          });
    } catch (e) {
      debugPrint("Payment error::: ${e.toString()}");
     //Printing this: TypeError: null: type 'Null' is not a subtype of type 'Object'
    }`

The popUp shows fine and am able to test for success and failed/cancelled cases however, the catch always get called whenever the popup shows. This is the error _**TypeError: null: type 'Null' is not a subtype of type 'Object'**_ and neither onClosed nor onSuccess get called and neither is any of the alert in the js script showing. Do you think am doing something wrong? Please help.

**Comment by Princewil** [comment]
Alright. I think it’s an error probably related to a flutter upgrade in
using dart types and Objects. I will work on it today and get back to you.

**Comment by Princewil** [comment]
Hey bro, I just realized this issue is similar to [#16](https://github.com/Princewil/flutter_paystack_plus/issues/16). 
I am yet to find where this error is coming from. However from my test onClosed and onSuccess get called. 
You can try the example repo found on the documentation.


In the meantime, I will close this issue since we already have a similar one already open and continue to work on find a fix.

**Comment by saintjab** [comment]
Thanks @Princewil for looking into it. I am not 100% sure where the issue was coming from but looking at the documentation `[example](https://pub.dev/documentation/flutter_paystack_plus/latest/)` and the [example](https://pub.dev/packages/flutter_paystack_plus/example) in the package page, I can see the latter returns from the `openPaystackPopup` which I assumes because of the initial error (when the popup shows), it was no longer calling any of the callbacks because it had already returned. Would be great if both can be synced.
