### ISSUE TITLE
Safe Area, Onsuccess, Onclosed Issues on Android App

### ISSUE THREAD

**Issue by raphaeldivine3028** [Princewil/flutter_paystack_plus#3]
Firstly, thank you so much for the effort put into this app. I sincerely appreciate it.

While most things work as expected, there are a few issues:

1. Safe Area: The payment screen is not respecting the safe area of my Android app, which includes the notification bar. See attached image.

2. The "Cancel Payment" payment is not responding. When clicked, nothing happens.

3. The Onsuccess/Onclosed isn't responding too. When a transaction isn't successful, the app is supposed to show a Not Successful Dialog, but this doesn't happen. That's similar to when a transaction is successful.

![paystack issues](https://github.com/Princewil/flutter_paystack_plus/assets/68448593/49eee90f-bc7c-42ed-ad0e-114849d02964)

This is part of the code relevant to my app.

```
 Future<void> startPayment() async {
    FlutterPaystackPlus.openPaystackPopup(
      publicKey: _payStackPublicKey,
      customerEmail: _getuserEmail(),
      context: Get.context,
      secretKey: _paystackSecretKey,
      amount: _amount,
      reference: _reference,
      currency: _currency,
      onClosed: () {
        log("Transaction Not Successful!");
        Dialogs.paymentNotSuccessful(errorMessage: "");
      },
      onSuccess: () async {
        log("Transaction Successful");
        premiumController.updatePremiumStatus(true);
        Dialogs.paymentSuccessful();
      },
    );
  }
```

```
Padding(
 padding: UIParameters.screenPadding,
 child: MainButton(
 onTap: () => controller.startPayment(),
 title: 'Upgrade Now',
 ),),
```

**Comment by Princewil** [comment]
Thanks for the appreciation and also for pointing these out, I will work on them.

**Comment by raphaeldivine3028** [comment]
Thank you so much. I'm looking forward to the cancel button fix

**Comment by Ade-Pyaar** [comment]
Nicely done.
I will also be on the lookout for the update concerning the onClosed and onSuccess functions.
👍

**Comment by gikwegbu** [comment]
For anyone still having issues with the `onClosed` and the `onSuccess` functionality, there are few things you'd need to do to make it work.

1. *onClosed Function*:
  From the `FlutterPaystackPlus.openPaystackPopup()`,   include the below in your `metadata`

```dart     
...
 metadata: {
    "cancel_action": "cancelurl.com",
  },
```

NB: Under the hood, the package uses a `Webview`; hence, the `NavigationDelegate` will be listening for the URL you passed as the value of the `cancel_action` you had entered above, to run the function @Princewil had created, check below:

NB: You must use the exact `cancelurl.com`, as @Princewil , from his code, is using it in his package...

```dart
...
NavigationDelegate(
    onNavigationRequest: (request) async {
      if (request.url.contains('cancelurl.com')) { // here is the cancel_action value being used...
        await _checkTransactionStatus(snapshot.data!.reference)
            .then((value) {
          Navigator.of(context).pop();
        });
      }
      if (request.url.contains('paystack.co/close')) {
        await _checkTransactionStatus(snapshot.data!.reference)
            .then((value) {
          Navigator.of(context).pop();
        });
      }
      if (request.url.contains(widget.callbackUrl)) { // Your callback url here
        await _checkTransactionStatus(snapshot.data!.reference)
            .then((value) {
          Navigator.of(context).pop();
        });
      }
      return NavigationDecision.navigate;
    },
  ),
)
```
NB: You don't need to worry yourself about the above function.


2. *onSuccess Function*:
For this to work, you'd need to provide the `callBackUrl`, found in your Paystack Dashboard.

NB: At the time of dropping this comment (which I'll update once @Princewil merges my PR), the `callBackUrl` is not hitting the `paystack initialize` endpoint, hence the `onSuccess()` won't be called. But once the merge is done, hopefully, it should get the `onSuccess()` function working again.


NB: To the best of my knowledge about `paystack`, the value you provide for the `callBackUrl`, overrides the value in your `paystack dashboard`.

E.g., if you have `george_is_happy.com` in your paystack dashboard and you pass `george_is_sad.com`, the latter (sad) will override the former (happy).

 Thanks. 🙏

**Comment by Princewil** [comment]
Thank you so much for your comment @gikwegbu and for solutions you gave. 

I will merge PR once I test it.

**Comment by Princewil** [comment]
All good now!

**Comment by gikwegbu** [comment]
Thanks chief.

Quick question: Will you be updating the package on PubDev? The changes
I've made are in my cache, and once my teammates pull from my branch, they
won't have those changes in theirs.

Once again,
Thanks for your help.

**Comment by Princewil** [comment]
I've updated the package so that you no longer need to manually add `"cancel_action": "cancelurl.com"` to the metadata. The package now adds this information automatically, which helps prevent spelling errors that could occur when adding it manually.

**Comment by Princewil** [comment]
I guess this reply is late. However I update the package on pub.
