### ISSUE TITLE
add Paymentchannel option

### ISSUE THREAD

**Issue by NBG-nero** [Princewil/flutter_paystack_plus#8]
Best Paystack plugin I've seen so far, only is is it open to bank transfer initially, add paymentChannel option, so User can specify if they want to include one,two or more paymentChannels, thank you

**Comment by Princewil** [comment]
Thanks for the tip! 😊

**Comment by ebenoasis** [comment]
Hello. Is there a way you could add the other payment channels such as momo? For some reasons I can only see the "Pay with car" method. Thanks

**Comment by Princewil** [comment]
You have to enable other payment options from your paystack dashboard
in-order to access them through the package.
So check your dashboard and be sure the options are enabled.

Thanks
